alphagov/notifications-python-client

client/__init__.py
client/base.py
client/errors.py
client/jwt.py
client/notifications.py
tests/client/test_jwt.py
tests/client/test_notifications_api_client.py

Implements token checking …
- all JWT code wrapped in library
- clients can construct and check tokens
Token checking:
Checks are as follows:
- signature
- expiry time (not in the future, not too old)
- request (METHOD / PATH)
- payload (optional)
Expiry time checking …
- JWT library already checks whether token is in the future so removed this check.

Adding decode token methods

---

notifications_python_client/notifications.py
tests/notifications_python_client/test_notifications_api_client.py
utils/make_api_call.py

- new call to fetch all notifications based on service
- handles filter params (status/template type)
- Utils script updated to handle new call

Added get_all_notifications to client

---

README.md

Squashed commits from @catherineheywood

Responses docs

---

integration_test/integration_tests.py
integration_test/schemas/v0/GET_notifications_return.json

Remove assert on contents of message.

Fix schema for get all notifications.

---

notifications_python_client/version.py

(should have gone in with previous PR, sorry)

bump version to 4.1.0 for python 2 support

---

integration_test/integration_tests.py

to wait for the notification to be persisted to the database. Temporary fix for the PAAS migration

Update integrations tests 

---

integration_test/integration_tests.py

Reverts alphagov/notifications-python-client#59

Revert "Update integrations tests "

---

README.md
integration_test/integration_tests.py
integration_test/schemas/v2/template_schemas.py
notifications_python_client/notifications.py
tests/notifications_python_client/test_notifications_api_client.py

Added unit and integration tests for v2 preview endpoints
Set the environment variables and run the tests -
./scripts/run_tests.sh 
./scripts/run_integration_tests.sh
[API Spec ](https://docs.google.com/document/d/1EuCipShwpZKVPQp3N0j7yRKazS34v5Bj5E9epl89iqY/edit#heading=h.pdggcx1vfo8x)

V2 post template preview

---

README.md

Updated the documentation for V2 endpoint get template by id and get template preview
Go through the README and check that wording, style, endpoints and error messages are correct. 
[API specification](https://docs.google.com/document/d/1EuCipShwpZKVPQp3N0j7yRKazS34v5Bj5E9epl89iqY/edit#heading=h.6vsyiqs899p)

Update readme - v2 get template by id and preview

---

integration_test/integration_tests.py
integration_test/schemas/v2/notification_schemas.py
scripts/generate_docker_env.sh
tox.ini

I'd like this merged before we release the new version to pypi :)

add integration test that sends a letter

---

CHANGELOG.md
notifications_python_client/__init__.py
tests/notifications_python_client/test_base_api_client.py

also set version to 4.4.0, not 4.5.0

add changelog

---

utils/make_api_call.py

so that you can use your bash history rather than re-entering things each time
example usage:
`PYTHONPATH=. python ./utils/make_api_call.py http://localhost:6011 [MY-API-KEY] create --type=sms --to=07123456789 --template=[SOME-UUID] --reference='' --personalisation='{"c": "yes", "b": "please include me", "a": [1, 2, "oiuoiuiouoiuiou"]}'`
Anything that is omitted will be prompted for like previous.

add --args to create test calls

---

.gitignore
notifications_python_client/__init__.py
notifications_python_client/notifications.py
tests/notifications_python_client/test_base_api_client.py
utils/make_api_call.py

The notification statistics was a spike that never materialised.

Remove notifications/statistics

---

README.md

To ensure all non-code uses of the word "Python" are capitalised.
- `README.md`
- `CHANGELOG.md`
- `notifications_python_client/__init__.py`
- `notifications_python_client/test_base_api_client.py`, function `test_user_agent_is_set`
- `notifications-python-client/scripts/generate_docker_env.sh`
- `notifications-python-client/tox.ini`
- `CONTRIBUTING.md`

Capitalised Python in introduction

---

README.md

So that both "Get Received Text Messages" sections are in the table of contents
- `README.md`
- `CHANGELOG.md`
- `notifications_python_client/__init__.py`
- `notifications_python_client/test_base_api_client.py`, function `test_user_agent_is_set`
- `notifications-python-client/scripts/generate_docker_env.sh`
- `notifications-python-client/tox.ini`
- `CONTRIBUTING.md`

Added Get Received Text Msgs to TOC

---

DOCUMENTATION.md

Some internal links in the file weren't working because they had a leading `/`.

Fix the internal links in DOCUMENTATION.md

---

DOCUMENTATION.md

Corrected the following links:
- Send a letter > Error codes > 400 > personalisation
- Get the status of all messages > Method > All messages > template_type
- Get the status of all messages > Method > All messages > status
- Get the status of all messages > Method > All messages > reference
- Get the status of all messages > Method > All messages > older_than
- Get the status of all messages > Method > One page of up to 250 messages > older_than
- Get the status of all messages > Method > One page of up to 250 messages > Most recent messages > status
- Get the status of all messages > Method > One page of up to 250 messages > Older messages > older_than
- Get the status of all messages > Method > One page of up to 250 messages > Older messages > status
- Get a template > Get a template …

Correct links

---

CHANGELOG.md
notifications_python_client/__init__.py
tests/notifications_python_client/test_base_api_client.py

version bump to 4.8.2 for pip10 fix

---

DOCUMENTATION.md

Follows: https://github.com/alphagov/notifications-ruby-client/pull/43

Add note about last 7 days in get all

---

DOCUMENTATION.md

Update python docs to reflect Java content changes
To be consistent with changes from Java tech docs.

Update python docs

---

DOCUMENTATION.md

Fix typo in documentation

---

DOCUMENTATION.md

Brings python docs in line with ruby docs in terms of language.

Updates to bring in line with Ruby docs

---

DOCUMENTATION.md

Adding the missing documentation to send precompiled letters.

Updated the documentation with how to send a precompiled letter.

---

DOCUMENTATION.md

Status table needed tweaking:
- Change pending virus check to "GOV.UK Notify is scanning the precompiled letter file for viruses"
- Remove code formatting in status column to fix text wrapping issue

Amend status table

---

CHANGELOG.md

don't put full stops in bullet points

---

.gitignore
DOCUMENTATION.md
Makefile

* docs tweaks
* gitignore tweaks
* removing pip-accel

misc dev fixes

---

CHANGELOG.md
DOCUMENTATION.md
notifications_python_client/__init__.py
notifications_python_client/utils.py
tests/notifications_python_client/test_base_api_client.py

refer to file, not document

---

CHANGELOG.md
DOCUMENTATION.md
notifications_python_client/__init__.py
notifications_python_client/utils.py
tests/notifications_python_client/test_base_api_client.py
tests/notifications_python_client/test_notifications_api_client.py
tests/notifications_python_client/test_utils.py
tests/test_files/test.csv

Concourse test pr 165

---

CHANGELOG.md
DOCUMENTATION.md
integration_test/integration_tests.py
integration_test/schemas/v2/template_schemas.py
notifications_python_client/__init__.py
tests/notifications_python_client/test_base_api_client.py

Add letter_contact_block to response for get template request

---

CHANGELOG.md
MANIFEST.in
notifications_python_client/__init__.py
notifications_python_client/errors.py
tests/notifications_python_client/test_base_api_client.py

Type hints test

---

DOCUMENTATION.md

Fix anchor link not working for new argument

---

DOCUMENTATION.md

Fix typo in heading (so anchor link works)

---

.git-blame-ignore-revs
.pre-commit-config.yaml
Makefile
integration_test/enums.py
integration_test/integration_tests.py
integration_test/schemas/v2/definitions.py
integration_test/schemas/v2/inbound_sms_schemas.py
integration_test/schemas/v2/notification_schemas.py
integration_test/schemas/v2/template_schemas.py
integration_test/schemas/v2/templates_schemas.py
notifications_python_client/__init__.py
notifications_python_client/authentication.py
notifications_python_client/base.py
notifications_python_client/errors.py
notifications_python_client/notifications.py
notifications_python_client/utils.py
pyproject.toml
requirements_for_test.txt
setup.cfg
setup.py
tests/conftest.py
tests/notifications_python_client/test_authentication.py
tests/notifications_python_client/test_base_api_client.py
tests/notifications_python_client/test_notifications_api_client.py
tests/notifications_python_client/test_utils.py
utils/make_api_call.py

Pre-commit, blacken, bump isort

---

DOCUMENTATION.md

This PR updates the ‘Send a file by email’ content to reflect the changes to defaults for:
* email as a password
* retention period
We should merge and deploy this on 12 April.

Update content for launch

---

.pre-commit-config.yaml
CHANGELOG.md
Makefile
notifications_python_client/__init__.py
notifications_python_client/authentication.py
notifications_python_client/base.py
notifications_python_client/notifications.py
pyproject.toml
requirements_for_test.txt
tests/notifications_python_client/test_notifications_api_client.py

Apply our formatting rules and tweak log messages
