alphagov/notifications-python-client

CONTRIBUTING.md, README.md
The `README`s for our clients should help you get set up making API calls to Notify quickly and easily. Therefore you don’t need to know about how to run the clients tests, or develop on it locally.
This commit rewrites the README to contain just the bare minimum you’d need to integrate the client into a new Python project.
This is sort of a strawperson that we can talk about.
The stuff specific to working on the client has moved into `CONTRIBUTING.md`.
=> Rewrite the documentation as a get-started guide

README.md, tests/notifications_python_client/test_authentication.py
they were only using freeze_time for half of the interaction - my completely untested assumption is that sometimes they'd fail, and sometimes succeed, depending on whether a second ticked over after time unfreezes.
just use freeze_time the whole time
=> make tests more stable

README.md
If you’re just getting started, the placeholder in the example doesn’t make sense. Better to understand the simple example first, then show a separate example for the personalisation.
- we don’t use them in the subsequent examples
- if you don’t know Python that well you might think they’re part of the syntax (they’re not)
=> Remove some confusing things from the documentation

README.md
The JSON returned by `get_notification_by_id` is wrapped in an object keyed by `data`. This was incorrectly omitted by the documentation.
=> Add missing `data` to get notification response

requirements_for_test.txt
As per: https://github.com/alphagov/notifications-api/commit/fa3d4413e7df77cdca7228e18325d0e8efd0bbc3
> requirements should be kept up to date to ensure we get bug fixes and
> new features as they come - particularly py.test, which we were
> running an 18 month old version for, and missing out on some useful
> xfail and fixture enhancements, among other things
Also installs pytest-xdist which includes the very useful `-f` flag to
re-run tests when files change. See:
https://github.com/pytest-dev/pytest-xdist#xdist-pytest-distributed-testing-plugin
=> Upgrade testing dependencies

Makefile
:grimacing:
stop passwords with bash control characters like semicolons breaking
the build. also stop passwords sitting in log files. WHOOPS
=> fix makefile - hide commands and wrap params in quotes 

CONTRIBUTING.md, MANIFEST.in, Makefile, docker/Dockerfile, integration_test/__init__.py, integration_test/integration_tests.py, notifications_python_client/__init__.py, notifications_python_client/authentication.py, notifications_python_client/base.py, notifications_python_client/errors.py, notifications_python_client/notifications.py, notifications_python_client/version.py, requirements.txt, scripts/generate_docker_env.sh, setup.cfg, setup.py, tests/conftest.py, tests/notifications_python_client/test_authentication.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py, tox.ini
🙌 🙌 🙌 🙌 🙌 
We now officially support python 2! Run tests on both 2.7 and 3.4 to ensure conformity
Biggest change is rather than the docker file stemming from python3.4:slim, it now just goes from debian:jessie (python3.4:slim inherits from that), and then apt-gets both python 2 and python 3, and then we use tox.
You can run tox locally by installing it in your env of choice (it doesn't matter, as when you use tox it'll create its own venvs for its tests), and then simply running `tox`, or it runs in docker through the command `make tox-with-docker`
Todo:
=> Python 2 support

tox.ini
tox manages its own env for #reasons, and on jenkins we need the
http_proxy variables to be set or we won't be able to access preview
to run the integration tests
=> pass through proxy settings to tox env

README.md
Send Messages section:
- Amended arguments to be channel-specific and copied into each channel section from the end of the Send Messages section
- Added phone number argument to text message channel section
Get Status... sections:
- Updated statuses for Letters to created, sending, failed, technical failure
- Amended failed statuses to be channel appropriate
Corrections:
- Added note saying that we support up to six lines and a postcode and this will be put in the address block of the letter
- Changed all address line 2 for letters to be required rather than optional
- Changed all fake addresses to 123 High street
=> Add Letters API to Python Docs

README.md
- Added short introduction saying what the client is and who should use it.
- Amended definition for personalisation in the letter section to better describe required and optional address lines and template fields
- Get the status of one message: Corrected address_line_2 needs to have `# required for letter`.
- Made arguments for the "Get statuses of all message with / without pagination" section collapsible
=> Python Docs Changes

README.md
* made the example rate limit not use team key (since that's not allowed for letters)
* changed the team api key and trial mode error messages to be more accurate
=> tweak letter error responses

CHANGELOG.md, README.md, integration_test/integration_tests.py, integration_test/schemas/v2/notification_schemas.py, notifications_python_client/__init__.py, notifications_python_client/notifications.py, scripts/generate_docker_env.sh, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py, tox.ini, utils/make_api_call.py
Updated integration and unit tests for python client
Reference - 
Step 6 from this story https://www.pivotaltracker.com/story/show/150440099
NOTE - Requires the email_reply_to_id API endpoint to be available before merging
=> Update post email with an optional email reply to

.github/PULL_REQUEST_TEMPLATE.md, notifications_python_client/__init__.py
We should clarify what our expectations are of external developers contributing to our codebase.
A good way to do this is through a pull request template, which lets developers check off what they’ve done. A lot of the GOV.UK frontend repos do this, eg https://github.com/alphagov/govuk_elements/blob/3c5c43a6fd4209cf2b6d180e7a5eadf6fa94c132/.github/PULL_REQUEST_TEMPLATE.md
This commit also documents how we do version numbering, so that an external developer would have a reasonable chance of being able to increment the version number in the right way.
=> Add pull request template

CHANGELOG.md, README.md, integration_test/integration_tests.py, integration_test/schemas/v2/notification_schemas.py, notifications_python_client/__init__.py, notifications_python_client/notifications.py, scripts/generate_docker_env.sh, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py, tox.ini, utils/make_api_call.py
When using the `send_sms_notification` function, you can now choose to specify which
sender you want the notification to come from by passing in an `sms_sender_id`. If this 
is not included, the sms notification will come from the default sender.
[Pivotal story](https://www.pivotaltracker.com/story/show/152106587)
=> Allow send_sms_notification to accept an sms_sender_id

integration_test/integration_tests.py
sms_sender_id isn't set on jenkins, but they were happily passing in None because the docker.env had set SMS_SENDER_ID to None.
=> Make integration tests fail if env is not set

notifications_python_client/__init__.py, requirements.txt, tests/notifications_python_client/test_base_api_client.py
The Digital Marketplace received a security alert on one of our repos that has the Notify Python client as a dependency. The version of `pyJWT` needs to be updated from `>=1` to `>=v1.5.1` to fix this vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2017-11424
- `notifications_python_client/__init__.py`
- `notifications_python_client/test_base_api_client.py`, function `test_user_agent_is_set`
(I don't think any new documentation required - let me know if anything should be added.)
Thanks!
=> Security fix for pyJWT

CHANGELOG.md, README.md, integration_test/integration_tests.py, integration_test/schemas/v2/notification_schemas.py, notifications_python_client/__init__.py, tests/notifications_python_client/test_base_api_client.py
The API has been updated so that the precompiled response to only includes the notification id and the client reference.
* Added a new schema for the precompiled response
* Updated Readme
* Updated the unit and integration tests
* Updated the change log
=> Updated the response to match that on API

CHANGELOG.md, DOCUMENTATION.md, notifications_python_client/__init__.py, notifications_python_client/notifications.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py
It's already possible to use the new Document Download integration
in the existing python client by setting a personalisation value to
`{"file": ...}`.
This simplifies the interface by recognizing file-like objects in
personalisation data and automatically reading/converting them to
the format expected by the Notify API:
```python
with open(<document-path>, 'rb') as f:
client.send_email_notification(..., personalisation={'doc': f})
```
=> Add support for attaching documents to email notifications

CHANGELOG.md, DOCUMENTATION.md, integration_test/schemas/v2/notification_schemas.py, notifications_python_client/__init__.py, tests/notifications_python_client/test_base_api_client.py
The `get_notification_by_id` and `get_all_notifications` methods now
return a new field, `created_by_name`, so this has been documented and
the schema for the integration tests updated.
The version has been bumped from `4.9.0` to `4.10.0` as a result.
=> Update responses when getting notifications and bump version 

DOCUMENTATION.md
`'document'` key sounds special and doesn't explain that the value that the placeholder ends up with is a link to an uploaded document.
=> Rename document upload placeholder in documentation

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/base.py, tests/notifications_python_client/test_base_api_client.py
Don't send an empty payload
Currently all our get/post/put/delete methods are an abstraction over a
generic `request` method which defaults to `None` for its `data` and
`params` arguments.
While each of the get/post/put/delete use only one of these arguments,
that has the uninteneded side-effect that GET requests are sent with a
body which is the json representation of `None`:
```python
>>> import json
>>> json.dumps(None)
'null'
```
This behaviour causes problems with Cloudfront which does not accept GET
requests that include a body and returns a 403 [1].
1: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#RequestCustom-get-body
=> Remove empty payload

CHANGELOG.md, DOCUMENTATION.md, integration_test/schemas/v2/template_schemas.py, notifications_python_client/__init__.py, tests/notifications_python_client/test_base_api_client.py
The name of the template is now returned by these two functions:
* `get_template_by_id()`
* `get_template_version()`
No changes to the code are necessary to make this work, but this PR updates the documentation and bumps the version. 
[Pivotal story](https://www.pivotaltracker.com/story/show/160020331)
=> Return 'name' when fetching a template

CHANGELOG.md, DOCUMENTATION.md, notifications_python_client/__init__.py, notifications_python_client/utils.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_utils.py
Since we can't guarantee that users will see the original 413 error message from document download we're implementing a file size check in the `prepare_upload` helper in all API clients.
This is technically a breaking change since it's replacing one exception with another, but we know `prepare_upload` is unused at the moment and after `5.0.1` we need to make it less scary for users to upgrade clients.
=> Add prepare upload file size check

DOCUMENTATION.md
Remove backticks from pre-compiled letter subheads. This is to make the sub-headings consistent with other sub-headings in the document
=> Remove backticks from precomp letter subheads

CHANGELOG.md, CONTRIBUTING.md, DOCUMENTATION.md, integration_test/integration_tests.py, integration_test/schemas/v2/notification_schemas.py, notifications_python_client/__init__.py, notifications_python_client/notifications.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py
Add an optional `postage` argument to send_precompiled_letter_notification method to allow our users to choose postage on precompiled letter they are sending.
=> Set postage for precompiled letters

CHANGELOG.md, DOCUMENTATION.md, integration_test/integration_tests.py, notifications_python_client/__init__.py, notifications_python_client/base.py, notifications_python_client/notifications.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py
Add new endpoint for get_letter_pdf (see https://github.com/alphagov/notifications-api/pull/2610). Still not sure whether we should make a new exception type (other than BadRequestError) for these specific errors, but I think this is okay as a first stab at it.
Content has been karlified
=> Get letter pdf

integration_test/integration_tests.py
=> use longer get pdf timeout in integration tests

notifications_python_client/__init__.py, notifications_python_client/authentication.py, notifications_python_client/errors.py, tests/notifications_python_client/test_authentication.py, tests/notifications_python_client/test_base_api_client.py
When we decrypt tokens we only allow HS256 so should raise an error rather then let the `jwt.exceptions.InvalidAlgorithmError` be uncaught.
Note, had to split up our main `decode_jwt_token` function because otherwise flake8 says it is too complex - pfffft!
=> Add `TokenAlgorithmError` for when algorithm is not HS256

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/authentication.py, notifications_python_client/errors.py, tests/notifications_python_client/test_authentication.py, tests/notifications_python_client/test_base_api_client.py
- We are seeing niche tokens come in (for example users setting the `aud` claim) which fail validation by jwt and raise exceptions that we aren't explicitely catching. We want to catch these exceptions and so therefore we catch all `InvalidTokenError`s to cover invalid tokens that aren't being caught by our more specific errors.
- Should all our errors to do with tokens also provide the link to the docs (on top of their more specific error message) as this seems generally useful?
=> Catch generic JWT InvalidTokenErrors

DOCUMENTATION.md
This PR changes the wording of 2 message status descriptions:
- mentioning the 72 hour period in the _Sending_ status makes it explicit that this a message that remains in this state for longer than a users expects is not 'stuck'
- not mentioning the 72 hour period in the _Phone not accepting messages right now_ status should reduce any confusion for users who see this status after <72 hours
This change was prompted by feedback from a user on x-gov Slack:
>We sent out a message last night and there were a few numbers that did not get it, on checking one, it gives the message: _"The provider could not deliver the message after trying for 72 hours. This can happen when the recipient’s phone is off..."_ Given it is not even 24 hours after the text was sent, any ideas why this report is …
=> Update status descriptions to help users understand the 72 hour period (Python)

DOCUMENTATION.md, integration_test/integration_tests.py, tests/notifications_python_client/test_notifications_api_client.py
This work is for this PR to work properly when deploying (otherwise client integrations tests will start failing): https://github.com/alphagov/notifications-api/pull/2751
=> Update tests and documentation so they handle postcode being validated

CHANGELOG.md, DOCUMENTATION.md, notifications_python_client/__init__.py, notifications_python_client/utils.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py, tests/notifications_python_client/test_utils.py, tests/test_files/test.csv
This PR adds an optional `is_csv` parameter to the `prepare_upload()` utility to allow clients to explicitly specify that the file they are uploading is a CSV. This provides a fix for an issue where uploads could not be saved as CSV and would always be saved as TXT. For more info, refer to: alphagov/notifications-python-client#164
=> Add is_csv kwarg to prepare_upload util

CONTRIBUTING.md, DOCUMENTATION.md, integration_test/integration_tests.py
We’re renaming the ‘Team and whitelist’ key in https://github.com/alphagov/notifications-admin/pull/3479
This commit updates the documentation to match.
=> Rename whitelist to guest list

DOCUMENTATION.md
**Do not merge until the rest of the navigation and headings PRs are ready**
To meet accessibility requirements, the Python client docs should only have one h1.
All additional h1s will change to h2s. All current h2s will change to h3s and so on.
=> Accessibility - fix heading structure

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/authentication.py, tests/notifications_python_client/test_authentication.py, tests/notifications_python_client/test_base_api_client.py
The latest version of PyJWT returns a string when encoding the token rather than bytes. This handles for either version of the jwt.encode method.
- [ x] I’ve written unit tests for these changes
- [x ] I’ve update the documentation in
- [x ] `DOCUMENTATION.md`
- [ x] `CHANGELOG.md`
- [ x] I’ve bumped the version number in
- [ x] `notifications_python_client/__init__.py`
- [ x] `notifications_python_client/test_base_api_client.py`, function `test_user_agent_is_set`
- [ x] I've added new environment variables to
=> Support PyJWT 2.0

CHANGELOG.md, notifications_python_client/__init__.py, setup.py, tests/notifications_python_client/test_base_api_client.py
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
set to >=3.6. note this is only respected by pip >= 9 so really old
setups will still be able to install old versions, but on their head
be it
=> use python_requires to stop pip installing on old py versions

.flake8, CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/authentication.py, notifications_python_client/base.py, notifications_python_client/errors.py, notifications_python_client/notifications.py, setup.py, tests/conftest.py, tests/notifications_python_client/test_authentication.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py
Removed two dependencies that are not needed any more - `future` and `monotonic`. See commits for details.
=> Delete deprecated dependencies

DOCUMENTATION.md
This PR updates the ‘Inbox not accepting messages right now’ email status description.
We’re making this change because a full inbox is not the only reason a user might get this status.
We’ve added the link to Service manual content because we should help users to understand why their content might be triggering a recipient’s spam filter.
The Service manual content could probably do with updating, but I’ll tackle this as a separate piece of work.
=> Update email status description

CHANGELOG.md, MANIFEST.in, notifications_python_client/__init__.py, notifications_python_client/errors.py, tests/notifications_python_client/test_base_api_client.py
The return type of `APIError.message` can [surprise users](https://github.com/alphagov/notifications-python-client/pull/172). By adding a type hint, we can make it more likely that users notice and handle it correctly.
Now that we have [dropped Python 2.7 support](https://github.com/alphagov/notifications-python-client/pull/185), Python 3.6 is the oldest Python version we support. So we are safe to start using Python 3.6 features, including type hints. Start with the errors module, because it's reasonably small.
~- [ ] I’ve written unit tests for these changes~
~- [ ] I’ve update the documentation in~
~- [ ] `DOCUMENTATION.md`~
~- [ ] `CHANGELOG.md`~
~- [ ] I've added new environment variables to~
~- [ ] `notifications-python-client/scripts/generate_docker_env.sh`~
~- [ ] …
=> Add type hints to the errors module

DOCUMENTATION.md
If a letter passes our validation but the print provider can not print the letter we should mark it as permanent-failure. An error message for permanent-failure is being added to the UI.
Technical-failure had the wrong message and validation failure will not show the pdf because the letter is in the wrong bucket.
=> Add permanent-failure status for letters.

CHANGELOG.md, DOCUMENTATION.md, notifications_python_client/__init__.py, notifications_python_client/notifications.py, tests/notifications_python_client/test_base_api_client.py, tests/notifications_python_client/test_notifications_api_client.py
https://govuk.zendesk.com/agent/tickets/4590242
Previously we would exclude these. We have a service [1] that:
- Uses the API to send initially.
- Uses the API to query failures.
- Uses the UI to manually resend.
- Uses the API to check the results.
While I'm not entirely convinced the last step is necessary, it
_is_ confhsing that what's visible in the UI is inconsistent with
the result from the API client. So, for at least that reason, this
adds the option to include notifications sent via a job.
Note that our Ruby client implicitly allows this already, by not
restricting the set of allowed parameters [2].
[1]: 53be32cd-69c1-4a72-a2e8-46ad8f768c61
[2]: https://github.com/alphagov/notifications-ruby-client/blob/328362a2df82cc0cb142618065467a032416cbd3/lib/notifications/client.rb#L101 …
=> Optionally include notifications from jobs

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/base.py, tests/notifications_python_client/test_base_api_client.py
https://www.pivotaltracker.com/story/show/178770155
Sets are just a special kind of list, so there's no reason why we
can't support them in POST data. Rather than peppering our code with
list(set) conversions (and testing them), it seems more pragmatic to
do it once where we can get the most benefit from it.
One use case for this will be POSTing permissions from Admin to API.
Admin uses sets for permissions most of the time, which means we get
an error if we try to POST them directly:
File "/Users/benthorner/.pyenv/versions/3.6.12/lib/python3.6/json/encoder.py", line 180, in default
o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
=> Support encoding sets in JSON POST data

CHANGELOG.md, DOCUMENTATION.md, notifications_python_client/__init__.py, notifications_python_client/utils.py, tests/notifications_python_client/test_notifications_api_client.py, tests/notifications_python_client/test_utils.py
Pass through `confirm_email_before_download` and `retention_period` parameters via `prepare_upload` calls so that clients can start to explicitly opt-in or opt-out of the new security features.
Bump client to v6.4.0
=> Add support for new doc download features

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/authentication.py, tests/notifications_python_client/test_authentication.py
If tokens are issued too far in the future, PyJWT >=2.6.0 now seems to throw ImmatureSignatureError rather than InvalidIssuedAtError, which is what we expect.
As we don't catch the new error correctly this bubbles up and causes a test failure on
test_should_reject_token_that_is_just_out_of_bounds_futured.
So now we're potentially validating `iat` in two places, depending on which version of PyJWT users have installed. We still need to do the check locally in case users are on <2.6.0.
=> Handle PyJWT 2.6.0 ImmatureSignatureError

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, MANIFEST.in, Makefile, notifications_python_client/__init__.py, setup.cfg, setup.py
Copied from #219 
---
Anyone trying to install the package from PyPI will also download unnecessary test files and utilities. The [latest package on PyPI](https://pypi.org/project/notifications-python-client/6.4.1/#files) only has a binary distribution wheel and it contains:
```
.
├── notifications_python_client-6.4.1.dist-info
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── WHEEL
│   └── top_level.txt
├── notifications_python_client
│   ├── __init__.py
│   ├── authentication.py
│   ├── base.py
│   ├── errors.py
│   ├── notifications.py
│   ├── py.typed
│   └── utils.py
├── integration_test    ← this folder should not be included
│   ├── __init__.py
│   ├── enums.py
│   ├── integration_tests.py
│   └── schemas
│       ├── __init__.py
│       └── v2
│           ├── __init__.py
│   …
```
=> Package without tests (by @ushkarev)

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/base.py
This should unlock performance benefits by utilising HTTP keep-alive to reuse one TCP connection between many requests. Quoth the docs:
[The Session object] across all requests [...] will use urllib3’s connection pooling. So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection).[^1]
Tested very unscientifically locally, 500 test notifications took 39 seconds, down from 52 seconds. (25% faster)
[^1]: https://requests.readthedocs.io/en/latest/user/advanced/
=> re-use a single request session

CHANGELOG.md, DOCUMENTATION.md, notifications_python_client/__init__.py, notifications_python_client/utils.py, tests/notifications_python_client/test_notifications_api_client.py, tests/notifications_python_client/test_utils.py
Allow services to specify the download filename for any files they send
by email.
This takes precedence over the `is_csv` parameter, which provided
limited and flawed functionality.
=> Allow setting custom filenames for documents

Makefile, pyproject.toml, requirements.txt
We have this `make` command in most of our other repos, for example the admin app: https://github.com/alphagov/notifications-admin/blob/main/Makefile#L85-L87
***
Depends on:
=> Add Makefile command to bump utils version

CHANGELOG.md, notifications_python_client/__init__.py, notifications_python_client/notifications.py
It was broken as it was calling itself instead of a get_received_texts() function, and so when trying to iterate over results, it would throw an error
=> Fix get_received_texts_iterator

Dockerfile, integration_test/integration_tests.py
[Trello card](https://trello.com/c/D1m5uleD/952-run-api-client-integration-tests-as-part-of-new-pipeline)
Some small updates to make the integration tests runnable in the dev environments via the new deploy pipeline.
[Tested in dev-a](https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/162) (5 times in a row to check for flakiness)
=> Make the integration tests compatible with the dev environments

integration_test/schemas/v2/notification_schemas.py
This updates the test schemas to reflect the fact that postage will soon be able to be "economy". This is done as a record of the data that can be returned, no changes to the code are necessary in order to start sending economy postage.
=> Update test schemas to account for economy postage
